# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BakedInterpolationSet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BakedDescriptor_pb2 as BakedDescriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='BakedInterpolationSet.proto',
  package='Persistance',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1b\x42\x61kedInterpolationSet.proto\x12\x0bPersistance\x1a\x15\x42\x61kedDescriptor.proto\"\xbb\x01\n\x15\x42\x61kedInterpolationSet\x12\'\n\x01\x61\x18\x01 \x01(\x0b\x32\x1c.Persistance.BakedDescriptor\x12\'\n\x01\x62\x18\x02 \x01(\x0b\x32\x1c.Persistance.BakedDescriptor\x12\'\n\x01\x63\x18\x03 \x01(\x0b\x32\x1c.Persistance.BakedDescriptor\x12\'\n\x01\x64\x18\x04 \x01(\x0b\x32\x1c.Persistance.BakedDescriptorb\x06proto3')
  ,
  dependencies=[BakedDescriptor__pb2.DESCRIPTOR,])




_BAKEDINTERPOLATIONSET = _descriptor.Descriptor(
  name='BakedInterpolationSet',
  full_name='Persistance.BakedInterpolationSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='Persistance.BakedInterpolationSet.a', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b', full_name='Persistance.BakedInterpolationSet.b', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='c', full_name='Persistance.BakedInterpolationSet.c', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='d', full_name='Persistance.BakedInterpolationSet.d', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=255,
)

_BAKEDINTERPOLATIONSET.fields_by_name['a'].message_type = BakedDescriptor__pb2._BAKEDDESCRIPTOR
_BAKEDINTERPOLATIONSET.fields_by_name['b'].message_type = BakedDescriptor__pb2._BAKEDDESCRIPTOR
_BAKEDINTERPOLATIONSET.fields_by_name['c'].message_type = BakedDescriptor__pb2._BAKEDDESCRIPTOR
_BAKEDINTERPOLATIONSET.fields_by_name['d'].message_type = BakedDescriptor__pb2._BAKEDDESCRIPTOR
DESCRIPTOR.message_types_by_name['BakedInterpolationSet'] = _BAKEDINTERPOLATIONSET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BakedInterpolationSet = _reflection.GeneratedProtocolMessageType('BakedInterpolationSet', (_message.Message,), dict(
  DESCRIPTOR = _BAKEDINTERPOLATIONSET,
  __module__ = 'BakedInterpolationSet_pb2'
  # @@protoc_insertion_point(class_scope:Persistance.BakedInterpolationSet)
  ))
_sym_db.RegisterMessage(BakedInterpolationSet)


# @@protoc_insertion_point(module_scope)
