# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BakedDescriptor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='BakedDescriptor.proto',
  package='Persistance',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15\x42\x61kedDescriptor.proto\x12\x0bPersistance\x1a\x0cVector.proto\"\x7f\n\x0f\x42\x61kedDescriptor\x12\x0c\n\x04grid\x18\x01 \x01(\x0c\x12&\n\x08position\x18\x02 \x01(\x0b\x32\x14.Persistance.Vector3\x12\'\n\tdirection\x18\x03 \x01(\x0b\x32\x14.Persistance.Vector3\x12\r\n\x05power\x18\x04 \x01(\x02\x62\x06proto3')
  ,
  dependencies=[Vector__pb2.DESCRIPTOR,])




_BAKEDDESCRIPTOR = _descriptor.Descriptor(
  name='BakedDescriptor',
  full_name='Persistance.BakedDescriptor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='grid', full_name='Persistance.BakedDescriptor.grid', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='Persistance.BakedDescriptor.position', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='direction', full_name='Persistance.BakedDescriptor.direction', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='power', full_name='Persistance.BakedDescriptor.power', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=179,
)

_BAKEDDESCRIPTOR.fields_by_name['position'].message_type = Vector__pb2._VECTOR3
_BAKEDDESCRIPTOR.fields_by_name['direction'].message_type = Vector__pb2._VECTOR3
DESCRIPTOR.message_types_by_name['BakedDescriptor'] = _BAKEDDESCRIPTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BakedDescriptor = _reflection.GeneratedProtocolMessageType('BakedDescriptor', (_message.Message,), dict(
  DESCRIPTOR = _BAKEDDESCRIPTOR,
  __module__ = 'BakedDescriptor_pb2'
  # @@protoc_insertion_point(class_scope:Persistance.BakedDescriptor)
  ))
_sym_db.RegisterMessage(BakedDescriptor)


# @@protoc_insertion_point(module_scope)
