# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DisneyDescriptor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DisneyDescriptor.proto',
  package='Persistance',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16\x44isneyDescriptor.proto\x12\x0bPersistance\x1a\x0cVector.proto\" \n\x10\x44isneyDescriptor\x12\x0c\n\x04grid\x18\x01 \x01(\x0c\x62\x06proto3')
  ,
  dependencies=[Vector__pb2.DESCRIPTOR,])




_DISNEYDESCRIPTOR = _descriptor.Descriptor(
  name='DisneyDescriptor',
  full_name='Persistance.DisneyDescriptor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='grid', full_name='Persistance.DisneyDescriptor.grid', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['DisneyDescriptor'] = _DISNEYDESCRIPTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DisneyDescriptor = _reflection.GeneratedProtocolMessageType('DisneyDescriptor', (_message.Message,), dict(
  DESCRIPTOR = _DISNEYDESCRIPTOR,
  __module__ = 'DisneyDescriptor_pb2'
  # @@protoc_insertion_point(class_scope:Persistance.DisneyDescriptor)
  ))
_sym_db.RegisterMessage(DisneyDescriptor)


# @@protoc_insertion_point(module_scope)
