# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ScatterSample.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ScatterSample.proto',
  package='Persistance',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13ScatterSample.proto\x12\x0bPersistance\x1a\x0cVector.proto\"z\n\rScatterSample\x12\x16\n\x0escene_setup_id\x18\x01 \x01(\x05\x12#\n\x05point\x18\x02 \x01(\x0b\x32\x14.Persistance.Vector3\x12,\n\x0eview_direction\x18\x03 \x01(\x0b\x32\x14.Persistance.Vector3b\x06proto3')
  ,
  dependencies=[Vector__pb2.DESCRIPTOR,])




_SCATTERSAMPLE = _descriptor.Descriptor(
  name='ScatterSample',
  full_name='Persistance.ScatterSample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scene_setup_id', full_name='Persistance.ScatterSample.scene_setup_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='point', full_name='Persistance.ScatterSample.point', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='view_direction', full_name='Persistance.ScatterSample.view_direction', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=172,
)

_SCATTERSAMPLE.fields_by_name['point'].message_type = Vector__pb2._VECTOR3
_SCATTERSAMPLE.fields_by_name['view_direction'].message_type = Vector__pb2._VECTOR3
DESCRIPTOR.message_types_by_name['ScatterSample'] = _SCATTERSAMPLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ScatterSample = _reflection.GeneratedProtocolMessageType('ScatterSample', (_message.Message,), dict(
  DESCRIPTOR = _SCATTERSAMPLE,
  __module__ = 'ScatterSample_pb2'
  # @@protoc_insertion_point(class_scope:Persistance.ScatterSample)
  ))
_sym_db.RegisterMessage(ScatterSample)


# @@protoc_insertion_point(module_scope)
