// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BakedInterpolationSet.proto

#include "BakedInterpolationSet.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_BakedDescriptor_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_BakedDescriptor_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_BakedDescriptor;
}  // namespace protobuf_BakedDescriptor_2eproto
namespace Persistance {
class BakedInterpolationSetDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<BakedInterpolationSet>
      _instance;
} _BakedInterpolationSet_default_instance_;
}  // namespace Persistance
namespace protobuf_BakedInterpolationSet_2eproto {
static void InitDefaultsBakedInterpolationSet() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Persistance::_BakedInterpolationSet_default_instance_;
    new (ptr) ::Persistance::BakedInterpolationSet();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Persistance::BakedInterpolationSet::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_BakedInterpolationSet =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsBakedInterpolationSet}, {
      &protobuf_BakedDescriptor_2eproto::scc_info_BakedDescriptor.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_BakedInterpolationSet.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Persistance::BakedInterpolationSet, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Persistance::BakedInterpolationSet, a_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Persistance::BakedInterpolationSet, b_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Persistance::BakedInterpolationSet, c_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Persistance::BakedInterpolationSet, d_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Persistance::BakedInterpolationSet)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::Persistance::_BakedInterpolationSet_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "BakedInterpolationSet.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\033BakedInterpolationSet.proto\022\013Persistan"
      "ce\032\025BakedDescriptor.proto\"\273\001\n\025BakedInter"
      "polationSet\022\'\n\001a\030\001 \001(\0132\034.Persistance.Bak"
      "edDescriptor\022\'\n\001b\030\002 \001(\0132\034.Persistance.Ba"
      "kedDescriptor\022\'\n\001c\030\003 \001(\0132\034.Persistance.B"
      "akedDescriptor\022\'\n\001d\030\004 \001(\0132\034.Persistance."
      "BakedDescriptorb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 263);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "BakedInterpolationSet.proto", &protobuf_RegisterTypes);
  ::protobuf_BakedDescriptor_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_BakedInterpolationSet_2eproto
namespace Persistance {

// ===================================================================

void BakedInterpolationSet::InitAsDefaultInstance() {
  ::Persistance::_BakedInterpolationSet_default_instance_._instance.get_mutable()->a_ = const_cast< ::Persistance::BakedDescriptor*>(
      ::Persistance::BakedDescriptor::internal_default_instance());
  ::Persistance::_BakedInterpolationSet_default_instance_._instance.get_mutable()->b_ = const_cast< ::Persistance::BakedDescriptor*>(
      ::Persistance::BakedDescriptor::internal_default_instance());
  ::Persistance::_BakedInterpolationSet_default_instance_._instance.get_mutable()->c_ = const_cast< ::Persistance::BakedDescriptor*>(
      ::Persistance::BakedDescriptor::internal_default_instance());
  ::Persistance::_BakedInterpolationSet_default_instance_._instance.get_mutable()->d_ = const_cast< ::Persistance::BakedDescriptor*>(
      ::Persistance::BakedDescriptor::internal_default_instance());
}
void BakedInterpolationSet::clear_a() {
  if (GetArenaNoVirtual() == NULL && a_ != NULL) {
    delete a_;
  }
  a_ = NULL;
}
void BakedInterpolationSet::clear_b() {
  if (GetArenaNoVirtual() == NULL && b_ != NULL) {
    delete b_;
  }
  b_ = NULL;
}
void BakedInterpolationSet::clear_c() {
  if (GetArenaNoVirtual() == NULL && c_ != NULL) {
    delete c_;
  }
  c_ = NULL;
}
void BakedInterpolationSet::clear_d() {
  if (GetArenaNoVirtual() == NULL && d_ != NULL) {
    delete d_;
  }
  d_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BakedInterpolationSet::kAFieldNumber;
const int BakedInterpolationSet::kBFieldNumber;
const int BakedInterpolationSet::kCFieldNumber;
const int BakedInterpolationSet::kDFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BakedInterpolationSet::BakedInterpolationSet()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_BakedInterpolationSet_2eproto::scc_info_BakedInterpolationSet.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Persistance.BakedInterpolationSet)
}
BakedInterpolationSet::BakedInterpolationSet(const BakedInterpolationSet& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_a()) {
    a_ = new ::Persistance::BakedDescriptor(*from.a_);
  } else {
    a_ = NULL;
  }
  if (from.has_b()) {
    b_ = new ::Persistance::BakedDescriptor(*from.b_);
  } else {
    b_ = NULL;
  }
  if (from.has_c()) {
    c_ = new ::Persistance::BakedDescriptor(*from.c_);
  } else {
    c_ = NULL;
  }
  if (from.has_d()) {
    d_ = new ::Persistance::BakedDescriptor(*from.d_);
  } else {
    d_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:Persistance.BakedInterpolationSet)
}

void BakedInterpolationSet::SharedCtor() {
  ::memset(&a_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&d_) -
      reinterpret_cast<char*>(&a_)) + sizeof(d_));
}

BakedInterpolationSet::~BakedInterpolationSet() {
  // @@protoc_insertion_point(destructor:Persistance.BakedInterpolationSet)
  SharedDtor();
}

void BakedInterpolationSet::SharedDtor() {
  if (this != internal_default_instance()) delete a_;
  if (this != internal_default_instance()) delete b_;
  if (this != internal_default_instance()) delete c_;
  if (this != internal_default_instance()) delete d_;
}

void BakedInterpolationSet::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* BakedInterpolationSet::descriptor() {
  ::protobuf_BakedInterpolationSet_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_BakedInterpolationSet_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const BakedInterpolationSet& BakedInterpolationSet::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_BakedInterpolationSet_2eproto::scc_info_BakedInterpolationSet.base);
  return *internal_default_instance();
}


void BakedInterpolationSet::Clear() {
// @@protoc_insertion_point(message_clear_start:Persistance.BakedInterpolationSet)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && a_ != NULL) {
    delete a_;
  }
  a_ = NULL;
  if (GetArenaNoVirtual() == NULL && b_ != NULL) {
    delete b_;
  }
  b_ = NULL;
  if (GetArenaNoVirtual() == NULL && c_ != NULL) {
    delete c_;
  }
  c_ = NULL;
  if (GetArenaNoVirtual() == NULL && d_ != NULL) {
    delete d_;
  }
  d_ = NULL;
  _internal_metadata_.Clear();
}

bool BakedInterpolationSet::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Persistance.BakedInterpolationSet)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .Persistance.BakedDescriptor a = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_a()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .Persistance.BakedDescriptor b = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_b()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .Persistance.BakedDescriptor c = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_c()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .Persistance.BakedDescriptor d = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_d()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Persistance.BakedInterpolationSet)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Persistance.BakedInterpolationSet)
  return false;
#undef DO_
}

void BakedInterpolationSet::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Persistance.BakedInterpolationSet)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .Persistance.BakedDescriptor a = 1;
  if (this->has_a()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_a(), output);
  }

  // .Persistance.BakedDescriptor b = 2;
  if (this->has_b()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_b(), output);
  }

  // .Persistance.BakedDescriptor c = 3;
  if (this->has_c()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->_internal_c(), output);
  }

  // .Persistance.BakedDescriptor d = 4;
  if (this->has_d()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->_internal_d(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Persistance.BakedInterpolationSet)
}

::google::protobuf::uint8* BakedInterpolationSet::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Persistance.BakedInterpolationSet)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .Persistance.BakedDescriptor a = 1;
  if (this->has_a()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_a(), deterministic, target);
  }

  // .Persistance.BakedDescriptor b = 2;
  if (this->has_b()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_b(), deterministic, target);
  }

  // .Persistance.BakedDescriptor c = 3;
  if (this->has_c()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->_internal_c(), deterministic, target);
  }

  // .Persistance.BakedDescriptor d = 4;
  if (this->has_d()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, this->_internal_d(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Persistance.BakedInterpolationSet)
  return target;
}

size_t BakedInterpolationSet::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Persistance.BakedInterpolationSet)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .Persistance.BakedDescriptor a = 1;
  if (this->has_a()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *a_);
  }

  // .Persistance.BakedDescriptor b = 2;
  if (this->has_b()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *b_);
  }

  // .Persistance.BakedDescriptor c = 3;
  if (this->has_c()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *c_);
  }

  // .Persistance.BakedDescriptor d = 4;
  if (this->has_d()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *d_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void BakedInterpolationSet::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Persistance.BakedInterpolationSet)
  GOOGLE_DCHECK_NE(&from, this);
  const BakedInterpolationSet* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const BakedInterpolationSet>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Persistance.BakedInterpolationSet)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Persistance.BakedInterpolationSet)
    MergeFrom(*source);
  }
}

void BakedInterpolationSet::MergeFrom(const BakedInterpolationSet& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Persistance.BakedInterpolationSet)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_a()) {
    mutable_a()->::Persistance::BakedDescriptor::MergeFrom(from.a());
  }
  if (from.has_b()) {
    mutable_b()->::Persistance::BakedDescriptor::MergeFrom(from.b());
  }
  if (from.has_c()) {
    mutable_c()->::Persistance::BakedDescriptor::MergeFrom(from.c());
  }
  if (from.has_d()) {
    mutable_d()->::Persistance::BakedDescriptor::MergeFrom(from.d());
  }
}

void BakedInterpolationSet::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Persistance.BakedInterpolationSet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BakedInterpolationSet::CopyFrom(const BakedInterpolationSet& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Persistance.BakedInterpolationSet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BakedInterpolationSet::IsInitialized() const {
  return true;
}

void BakedInterpolationSet::Swap(BakedInterpolationSet* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BakedInterpolationSet::InternalSwap(BakedInterpolationSet* other) {
  using std::swap;
  swap(a_, other->a_);
  swap(b_, other->b_);
  swap(c_, other->c_);
  swap(d_, other->d_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata BakedInterpolationSet::GetMetadata() const {
  protobuf_BakedInterpolationSet_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_BakedInterpolationSet_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Persistance
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Persistance::BakedInterpolationSet* Arena::CreateMaybeMessage< ::Persistance::BakedInterpolationSet >(Arena* arena) {
  return Arena::CreateInternal< ::Persistance::BakedInterpolationSet >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
