// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BakedInterpolationSet.proto

#ifndef PROTOBUF_INCLUDED_BakedInterpolationSet_2eproto
#define PROTOBUF_INCLUDED_BakedInterpolationSet_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "BakedDescriptor.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_BakedInterpolationSet_2eproto 

namespace protobuf_BakedInterpolationSet_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_BakedInterpolationSet_2eproto
namespace Persistance {
class BakedInterpolationSet;
class BakedInterpolationSetDefaultTypeInternal;
extern BakedInterpolationSetDefaultTypeInternal _BakedInterpolationSet_default_instance_;
}  // namespace Persistance
namespace google {
namespace protobuf {
template<> ::Persistance::BakedInterpolationSet* Arena::CreateMaybeMessage<::Persistance::BakedInterpolationSet>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace Persistance {

// ===================================================================

class BakedInterpolationSet : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Persistance.BakedInterpolationSet) */ {
 public:
  BakedInterpolationSet();
  virtual ~BakedInterpolationSet();

  BakedInterpolationSet(const BakedInterpolationSet& from);

  inline BakedInterpolationSet& operator=(const BakedInterpolationSet& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BakedInterpolationSet(BakedInterpolationSet&& from) noexcept
    : BakedInterpolationSet() {
    *this = ::std::move(from);
  }

  inline BakedInterpolationSet& operator=(BakedInterpolationSet&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BakedInterpolationSet& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BakedInterpolationSet* internal_default_instance() {
    return reinterpret_cast<const BakedInterpolationSet*>(
               &_BakedInterpolationSet_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(BakedInterpolationSet* other);
  friend void swap(BakedInterpolationSet& a, BakedInterpolationSet& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BakedInterpolationSet* New() const final {
    return CreateMaybeMessage<BakedInterpolationSet>(NULL);
  }

  BakedInterpolationSet* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BakedInterpolationSet>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BakedInterpolationSet& from);
  void MergeFrom(const BakedInterpolationSet& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BakedInterpolationSet* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .Persistance.BakedDescriptor a = 1;
  bool has_a() const;
  void clear_a();
  static const int kAFieldNumber = 1;
  private:
  const ::Persistance::BakedDescriptor& _internal_a() const;
  public:
  const ::Persistance::BakedDescriptor& a() const;
  ::Persistance::BakedDescriptor* release_a();
  ::Persistance::BakedDescriptor* mutable_a();
  void set_allocated_a(::Persistance::BakedDescriptor* a);

  // .Persistance.BakedDescriptor b = 2;
  bool has_b() const;
  void clear_b();
  static const int kBFieldNumber = 2;
  private:
  const ::Persistance::BakedDescriptor& _internal_b() const;
  public:
  const ::Persistance::BakedDescriptor& b() const;
  ::Persistance::BakedDescriptor* release_b();
  ::Persistance::BakedDescriptor* mutable_b();
  void set_allocated_b(::Persistance::BakedDescriptor* b);

  // .Persistance.BakedDescriptor c = 3;
  bool has_c() const;
  void clear_c();
  static const int kCFieldNumber = 3;
  private:
  const ::Persistance::BakedDescriptor& _internal_c() const;
  public:
  const ::Persistance::BakedDescriptor& c() const;
  ::Persistance::BakedDescriptor* release_c();
  ::Persistance::BakedDescriptor* mutable_c();
  void set_allocated_c(::Persistance::BakedDescriptor* c);

  // .Persistance.BakedDescriptor d = 4;
  bool has_d() const;
  void clear_d();
  static const int kDFieldNumber = 4;
  private:
  const ::Persistance::BakedDescriptor& _internal_d() const;
  public:
  const ::Persistance::BakedDescriptor& d() const;
  ::Persistance::BakedDescriptor* release_d();
  ::Persistance::BakedDescriptor* mutable_d();
  void set_allocated_d(::Persistance::BakedDescriptor* d);

  // @@protoc_insertion_point(class_scope:Persistance.BakedInterpolationSet)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::Persistance::BakedDescriptor* a_;
  ::Persistance::BakedDescriptor* b_;
  ::Persistance::BakedDescriptor* c_;
  ::Persistance::BakedDescriptor* d_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_BakedInterpolationSet_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BakedInterpolationSet

// .Persistance.BakedDescriptor a = 1;
inline bool BakedInterpolationSet::has_a() const {
  return this != internal_default_instance() && a_ != NULL;
}
inline const ::Persistance::BakedDescriptor& BakedInterpolationSet::_internal_a() const {
  return *a_;
}
inline const ::Persistance::BakedDescriptor& BakedInterpolationSet::a() const {
  const ::Persistance::BakedDescriptor* p = a_;
  // @@protoc_insertion_point(field_get:Persistance.BakedInterpolationSet.a)
  return p != NULL ? *p : *reinterpret_cast<const ::Persistance::BakedDescriptor*>(
      &::Persistance::_BakedDescriptor_default_instance_);
}
inline ::Persistance::BakedDescriptor* BakedInterpolationSet::release_a() {
  // @@protoc_insertion_point(field_release:Persistance.BakedInterpolationSet.a)
  
  ::Persistance::BakedDescriptor* temp = a_;
  a_ = NULL;
  return temp;
}
inline ::Persistance::BakedDescriptor* BakedInterpolationSet::mutable_a() {
  
  if (a_ == NULL) {
    auto* p = CreateMaybeMessage<::Persistance::BakedDescriptor>(GetArenaNoVirtual());
    a_ = p;
  }
  // @@protoc_insertion_point(field_mutable:Persistance.BakedInterpolationSet.a)
  return a_;
}
inline void BakedInterpolationSet::set_allocated_a(::Persistance::BakedDescriptor* a) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(a_);
  }
  if (a) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      a = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, a, submessage_arena);
    }
    
  } else {
    
  }
  a_ = a;
  // @@protoc_insertion_point(field_set_allocated:Persistance.BakedInterpolationSet.a)
}

// .Persistance.BakedDescriptor b = 2;
inline bool BakedInterpolationSet::has_b() const {
  return this != internal_default_instance() && b_ != NULL;
}
inline const ::Persistance::BakedDescriptor& BakedInterpolationSet::_internal_b() const {
  return *b_;
}
inline const ::Persistance::BakedDescriptor& BakedInterpolationSet::b() const {
  const ::Persistance::BakedDescriptor* p = b_;
  // @@protoc_insertion_point(field_get:Persistance.BakedInterpolationSet.b)
  return p != NULL ? *p : *reinterpret_cast<const ::Persistance::BakedDescriptor*>(
      &::Persistance::_BakedDescriptor_default_instance_);
}
inline ::Persistance::BakedDescriptor* BakedInterpolationSet::release_b() {
  // @@protoc_insertion_point(field_release:Persistance.BakedInterpolationSet.b)
  
  ::Persistance::BakedDescriptor* temp = b_;
  b_ = NULL;
  return temp;
}
inline ::Persistance::BakedDescriptor* BakedInterpolationSet::mutable_b() {
  
  if (b_ == NULL) {
    auto* p = CreateMaybeMessage<::Persistance::BakedDescriptor>(GetArenaNoVirtual());
    b_ = p;
  }
  // @@protoc_insertion_point(field_mutable:Persistance.BakedInterpolationSet.b)
  return b_;
}
inline void BakedInterpolationSet::set_allocated_b(::Persistance::BakedDescriptor* b) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(b_);
  }
  if (b) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      b = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, b, submessage_arena);
    }
    
  } else {
    
  }
  b_ = b;
  // @@protoc_insertion_point(field_set_allocated:Persistance.BakedInterpolationSet.b)
}

// .Persistance.BakedDescriptor c = 3;
inline bool BakedInterpolationSet::has_c() const {
  return this != internal_default_instance() && c_ != NULL;
}
inline const ::Persistance::BakedDescriptor& BakedInterpolationSet::_internal_c() const {
  return *c_;
}
inline const ::Persistance::BakedDescriptor& BakedInterpolationSet::c() const {
  const ::Persistance::BakedDescriptor* p = c_;
  // @@protoc_insertion_point(field_get:Persistance.BakedInterpolationSet.c)
  return p != NULL ? *p : *reinterpret_cast<const ::Persistance::BakedDescriptor*>(
      &::Persistance::_BakedDescriptor_default_instance_);
}
inline ::Persistance::BakedDescriptor* BakedInterpolationSet::release_c() {
  // @@protoc_insertion_point(field_release:Persistance.BakedInterpolationSet.c)
  
  ::Persistance::BakedDescriptor* temp = c_;
  c_ = NULL;
  return temp;
}
inline ::Persistance::BakedDescriptor* BakedInterpolationSet::mutable_c() {
  
  if (c_ == NULL) {
    auto* p = CreateMaybeMessage<::Persistance::BakedDescriptor>(GetArenaNoVirtual());
    c_ = p;
  }
  // @@protoc_insertion_point(field_mutable:Persistance.BakedInterpolationSet.c)
  return c_;
}
inline void BakedInterpolationSet::set_allocated_c(::Persistance::BakedDescriptor* c) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(c_);
  }
  if (c) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      c = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, c, submessage_arena);
    }
    
  } else {
    
  }
  c_ = c;
  // @@protoc_insertion_point(field_set_allocated:Persistance.BakedInterpolationSet.c)
}

// .Persistance.BakedDescriptor d = 4;
inline bool BakedInterpolationSet::has_d() const {
  return this != internal_default_instance() && d_ != NULL;
}
inline const ::Persistance::BakedDescriptor& BakedInterpolationSet::_internal_d() const {
  return *d_;
}
inline const ::Persistance::BakedDescriptor& BakedInterpolationSet::d() const {
  const ::Persistance::BakedDescriptor* p = d_;
  // @@protoc_insertion_point(field_get:Persistance.BakedInterpolationSet.d)
  return p != NULL ? *p : *reinterpret_cast<const ::Persistance::BakedDescriptor*>(
      &::Persistance::_BakedDescriptor_default_instance_);
}
inline ::Persistance::BakedDescriptor* BakedInterpolationSet::release_d() {
  // @@protoc_insertion_point(field_release:Persistance.BakedInterpolationSet.d)
  
  ::Persistance::BakedDescriptor* temp = d_;
  d_ = NULL;
  return temp;
}
inline ::Persistance::BakedDescriptor* BakedInterpolationSet::mutable_d() {
  
  if (d_ == NULL) {
    auto* p = CreateMaybeMessage<::Persistance::BakedDescriptor>(GetArenaNoVirtual());
    d_ = p;
  }
  // @@protoc_insertion_point(field_mutable:Persistance.BakedInterpolationSet.d)
  return d_;
}
inline void BakedInterpolationSet::set_allocated_d(::Persistance::BakedDescriptor* d) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(d_);
  }
  if (d) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      d = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, d, submessage_arena);
    }
    
  } else {
    
  }
  d_ = d;
  // @@protoc_insertion_point(field_set_allocated:Persistance.BakedInterpolationSet.d)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Persistance

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_BakedInterpolationSet_2eproto
