// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DisneyDescriptor.proto

#include "DisneyDescriptor.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace Persistance {
class DisneyDescriptorDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DisneyDescriptor>
      _instance;
} _DisneyDescriptor_default_instance_;
}  // namespace Persistance
namespace protobuf_DisneyDescriptor_2eproto {
static void InitDefaultsDisneyDescriptor() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Persistance::_DisneyDescriptor_default_instance_;
    new (ptr) ::Persistance::DisneyDescriptor();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Persistance::DisneyDescriptor::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_DisneyDescriptor =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsDisneyDescriptor}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_DisneyDescriptor.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Persistance::DisneyDescriptor, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Persistance::DisneyDescriptor, grid_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Persistance::DisneyDescriptor)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::Persistance::_DisneyDescriptor_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "DisneyDescriptor.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\026DisneyDescriptor.proto\022\013Persistance\032\014V"
      "ector.proto\" \n\020DisneyDescriptor\022\014\n\004grid\030"
      "\001 \001(\014b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 93);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "DisneyDescriptor.proto", &protobuf_RegisterTypes);
  ::protobuf_Vector_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_DisneyDescriptor_2eproto
namespace Persistance {

// ===================================================================

void DisneyDescriptor::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DisneyDescriptor::kGridFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DisneyDescriptor::DisneyDescriptor()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_DisneyDescriptor_2eproto::scc_info_DisneyDescriptor.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Persistance.DisneyDescriptor)
}
DisneyDescriptor::DisneyDescriptor(const DisneyDescriptor& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  grid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.grid().size() > 0) {
    grid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.grid_);
  }
  // @@protoc_insertion_point(copy_constructor:Persistance.DisneyDescriptor)
}

void DisneyDescriptor::SharedCtor() {
  grid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

DisneyDescriptor::~DisneyDescriptor() {
  // @@protoc_insertion_point(destructor:Persistance.DisneyDescriptor)
  SharedDtor();
}

void DisneyDescriptor::SharedDtor() {
  grid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void DisneyDescriptor::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* DisneyDescriptor::descriptor() {
  ::protobuf_DisneyDescriptor_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DisneyDescriptor_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const DisneyDescriptor& DisneyDescriptor::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_DisneyDescriptor_2eproto::scc_info_DisneyDescriptor.base);
  return *internal_default_instance();
}


void DisneyDescriptor::Clear() {
// @@protoc_insertion_point(message_clear_start:Persistance.DisneyDescriptor)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  grid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool DisneyDescriptor::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Persistance.DisneyDescriptor)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes grid = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_grid()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Persistance.DisneyDescriptor)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Persistance.DisneyDescriptor)
  return false;
#undef DO_
}

void DisneyDescriptor::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Persistance.DisneyDescriptor)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes grid = 1;
  if (this->grid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->grid(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Persistance.DisneyDescriptor)
}

::google::protobuf::uint8* DisneyDescriptor::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Persistance.DisneyDescriptor)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes grid = 1;
  if (this->grid().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->grid(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Persistance.DisneyDescriptor)
  return target;
}

size_t DisneyDescriptor::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Persistance.DisneyDescriptor)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes grid = 1;
  if (this->grid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->grid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DisneyDescriptor::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Persistance.DisneyDescriptor)
  GOOGLE_DCHECK_NE(&from, this);
  const DisneyDescriptor* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DisneyDescriptor>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Persistance.DisneyDescriptor)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Persistance.DisneyDescriptor)
    MergeFrom(*source);
  }
}

void DisneyDescriptor::MergeFrom(const DisneyDescriptor& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Persistance.DisneyDescriptor)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.grid().size() > 0) {

    grid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.grid_);
  }
}

void DisneyDescriptor::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Persistance.DisneyDescriptor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DisneyDescriptor::CopyFrom(const DisneyDescriptor& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Persistance.DisneyDescriptor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DisneyDescriptor::IsInitialized() const {
  return true;
}

void DisneyDescriptor::Swap(DisneyDescriptor* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DisneyDescriptor::InternalSwap(DisneyDescriptor* other) {
  using std::swap;
  grid_.Swap(&other->grid_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata DisneyDescriptor::GetMetadata() const {
  protobuf_DisneyDescriptor_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DisneyDescriptor_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Persistance
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Persistance::DisneyDescriptor* Arena::CreateMaybeMessage< ::Persistance::DisneyDescriptor >(Arena* arena) {
  return Arena::CreateInternal< ::Persistance::DisneyDescriptor >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
