// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DisneyDescriptor.proto

#ifndef PROTOBUF_INCLUDED_DisneyDescriptor_2eproto
#define PROTOBUF_INCLUDED_DisneyDescriptor_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Vector.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_DisneyDescriptor_2eproto 

namespace protobuf_DisneyDescriptor_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_DisneyDescriptor_2eproto
namespace Persistance {
class DisneyDescriptor;
class DisneyDescriptorDefaultTypeInternal;
extern DisneyDescriptorDefaultTypeInternal _DisneyDescriptor_default_instance_;
}  // namespace Persistance
namespace google {
namespace protobuf {
template<> ::Persistance::DisneyDescriptor* Arena::CreateMaybeMessage<::Persistance::DisneyDescriptor>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace Persistance {

// ===================================================================

class DisneyDescriptor : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Persistance.DisneyDescriptor) */ {
 public:
  DisneyDescriptor();
  virtual ~DisneyDescriptor();

  DisneyDescriptor(const DisneyDescriptor& from);

  inline DisneyDescriptor& operator=(const DisneyDescriptor& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DisneyDescriptor(DisneyDescriptor&& from) noexcept
    : DisneyDescriptor() {
    *this = ::std::move(from);
  }

  inline DisneyDescriptor& operator=(DisneyDescriptor&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DisneyDescriptor& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DisneyDescriptor* internal_default_instance() {
    return reinterpret_cast<const DisneyDescriptor*>(
               &_DisneyDescriptor_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(DisneyDescriptor* other);
  friend void swap(DisneyDescriptor& a, DisneyDescriptor& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DisneyDescriptor* New() const final {
    return CreateMaybeMessage<DisneyDescriptor>(NULL);
  }

  DisneyDescriptor* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DisneyDescriptor>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DisneyDescriptor& from);
  void MergeFrom(const DisneyDescriptor& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DisneyDescriptor* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes grid = 1;
  void clear_grid();
  static const int kGridFieldNumber = 1;
  const ::std::string& grid() const;
  void set_grid(const ::std::string& value);
  #if LANG_CXX11
  void set_grid(::std::string&& value);
  #endif
  void set_grid(const char* value);
  void set_grid(const void* value, size_t size);
  ::std::string* mutable_grid();
  ::std::string* release_grid();
  void set_allocated_grid(::std::string* grid);

  // @@protoc_insertion_point(class_scope:Persistance.DisneyDescriptor)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr grid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_DisneyDescriptor_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DisneyDescriptor

// bytes grid = 1;
inline void DisneyDescriptor::clear_grid() {
  grid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DisneyDescriptor::grid() const {
  // @@protoc_insertion_point(field_get:Persistance.DisneyDescriptor.grid)
  return grid_.GetNoArena();
}
inline void DisneyDescriptor::set_grid(const ::std::string& value) {
  
  grid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Persistance.DisneyDescriptor.grid)
}
#if LANG_CXX11
inline void DisneyDescriptor::set_grid(::std::string&& value) {
  
  grid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Persistance.DisneyDescriptor.grid)
}
#endif
inline void DisneyDescriptor::set_grid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  grid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Persistance.DisneyDescriptor.grid)
}
inline void DisneyDescriptor::set_grid(const void* value, size_t size) {
  
  grid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Persistance.DisneyDescriptor.grid)
}
inline ::std::string* DisneyDescriptor::mutable_grid() {
  
  // @@protoc_insertion_point(field_mutable:Persistance.DisneyDescriptor.grid)
  return grid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DisneyDescriptor::release_grid() {
  // @@protoc_insertion_point(field_release:Persistance.DisneyDescriptor.grid)
  
  return grid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DisneyDescriptor::set_allocated_grid(::std::string* grid) {
  if (grid != NULL) {
    
  } else {
    
  }
  grid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), grid);
  // @@protoc_insertion_point(field_set_allocated:Persistance.DisneyDescriptor.grid)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Persistance

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_DisneyDescriptor_2eproto
